### ISSUE TITLE
[홈] RetrieveHome 메소드가 suspend 불 필요하게 많은 걸로 추측됨

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [FONE1light/fone-backend-jdsl#243]
어제(23.3.18) 언급은 했으나,

HomeController.RetrieveHome 메소드에 불 필요한 suspend가 많이 있는 걸로 의심이 됩니다.

제 의심이 맞다면, coroutine은 기본적으로 순차적으로 진행되어 의존 관계가 없는 suspend 함수들도 의존성이 있어 보입니다.

많은 요청이 있는 경우 전체적 throughput에는 큰 차이가 없을 것으로 예상되나 최소 응답 속도에는 유의미한 차이가 있지 않을까 추측이 되네요.

직접 테스트하기에는 아직 어려움이 있어 제가 임의로 Unit 테스트로 예상되는 IO 활동을 mock 해봤으며 검토바랍니다.

실제 코드에 변경 사항은 최소화했으며 간단하게 리팩토링 된 클래스와 비교할 수 있는 형태의 테스트를 작성했습니다.

**Comment by DoodlesOnMyFood** [comment]
근데 푸시가 안되네요. 다음에 푸시를 하도록하겠습니다.

**Comment by sinkyoungdeok** [comment]
푸시권한이 없나요? 어떤 브랜치로 푸시 하셨나요?

**Comment by DoodlesOnMyFood** [comment]
새로운 브랜치 만들고 푸시해 봤으나, 그냥 프로젝트 수정권한 자체가 없어보입니다. 지금도 아무 브랜치에 파일 수정 눌러보면 깃허브에서 권한이 없어서 수정 사항 포크 후 수정된다고 알려주네요.

**Comment by sinkyoungdeok** [comment]
한번더 해보실 수 있을까요?

**Comment by DoodlesOnMyFood** [comment]
네 이제 코드 수정할 수 있는걸로 보이네요. 퇴근 후 PR올리겠습니다.
